name: Test Cypress Real World App

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          repository: cypress-io/cypress-realworld-app
          ref: develop
          path: ./cloned-repo

      - name: Install Dependencies and Run Dev Server
        run: |
          cd cloned-repo
          yarn install
          yarn dev & sleep 40 && curl http://localhost:3000

      - name: Install ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install google-chrome-stable
          sudo apt-get install xvfb
          sudo apt-get install -y unzip
          wget -N https://chromedriver.storage.googleapis.com/LATEST_RELEASE
          export CHROMEDRIVER_VERSION=$(cat LATEST_RELEASE)
          wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chown root:root /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Install Dependencies and Run Tests
        run: |
          npm install
          npm run test &> test_output.txt

      - name: Deploy Results to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: allure-report/
